name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build notice
        run: |
          ls -lsa
          docker compose build
          docker images
          echo "Build by @${{ github.actor }}."
